### ISSUE TITLE
Working on master?

### ISSUE THREAD

**Issue by esbullington** [LeoTestard/rustlex#6]
There's no mention on the Rust version in the Readme.  Are you trying to get rustlex working with 0.11-pre?  If so, looks like there might be a few issues still, at least with the very latest master.

This is a *very* cool project and  I look forward to creating a toy language using Rust and restlex.  It's also given me an idea for a bitstring pattern matching macro.

Anyway, I'd be happy to submit a pull request with the updates to work with master if that's what you're trying to do.

**Comment by LeoTestard** [comment]
This issue seems rather old and out of date, so I'll close it. Feel free to re-open it/open a new one if there is still some issue.
